version: '2'
services:
  nginx:
    image: docker.io/devilbox/nginx-stable:alpine
    container_name: bowie-container-nginx
    restart: always
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=app
    volumes:
      - .:/var/www/default
      - ./public:/var/www/default/htdocs
    ports:
      - 22777:80
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bowie-container-app
    volumes:
      - .:/var/www/default
      - ./public:/var/www/default/htdocs
  redis:
    image: library/redis:7.0.5-alpine
    container_name: bowie-container-redis
    restart: always
    volumes:
      - redis-data:/data
volumes:
  redis-data:
